name: gcc-14
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: build-test on gcc-${{ matrix.gcc_version }} with build type ${{ matrix.build_type }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        gcc_version: [14.2]

    container:
      image: gcc:${{ matrix.gcc_version }}

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential cmake git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure cmake
        run: cmake -B build -S . -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure


